name: passguard_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.70.2 
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.4
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.1
  http: ^1.3.0
  crypto: ^3.0.6
  word_generator: ^0.4.6
  encrypt: ^5.0.1
  pointycastle: ^3.2.0
  argon2: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/bgImage.webp
    - assets/logo.png
    - assets/vide1.gif
    - assets/managerPass.png
    - assets/alert.png
    - assets/add_user.png
    - assets/loginBg.jpg
    - assets/redX.png
    - assets/check.png
    - assets/bgDashPass.png


